Modify 'web suite' link to be a dropdown menu containing apps
openflighthpc/flight-landing-page pull request #16
Opened 2022-04-05 12:22 UTC by VoxSecundus

This PR introduces a change to the landing page navbar. The conditionally used `Web Suite` button is now a split dropdown button. The old button functionality remains the same, but it is now followed by a dropdown button listing the available webapps.

2022-04-05 15:21 UTC, benarmston requested changes
Code-wise this looks right.  I have some styling comments to make and I'm going to expand the scope of this work too.

Having the items in the menu bold doesn't look quite right.  In particular, it doesn't allow to tell which item I'm hovering over.

![image](https://user-images.githubusercontent.com/287050/161787436-888be265-9b93-4004-b622-9870b8032bc9.png)

I think these would look better with the app icon included too.

![image](https://user-images.githubusercontent.com/287050/161788020-36262d97-dc43-4ce8-a5b9-d2b78cc0b5a6.png)

And for the increase in scope, also please include the icon in the sidebar too.

![image](https://user-images.githubusercontent.com/287050/161788104-1df5e6db-ca03-4609-ad7c-314019a5b2d6.png)

2022-04-05 16:29 UTC, VoxSecundus commented
Before I replicate the updated dropdown in the webapp components repo, do these look alright? The icons are set to be fixed width so that the app titles line up.
![Screenshot_2022-04-05_17-28-19](https://user-images.githubusercontent.com/12374447/161801769-99664cc6-ca6f-4abb-9383-7edcf54bd602.png)

![Screenshot_2022-04-05_17-28-12](https://user-images.githubusercontent.com/12374447/161801774-98ef3da9-b563-4db8-866a-42c6cb2deea9.png)

2022-04-06 16:14 UTC, benarmston requested changes
The icons are now fixed.  I've found a couple more issues for you to fix.  Could you also take a look at the styling when the alces branding is enabled.  The dropdown arrow isn't visible; the menu is escaping off the edge of the browser and the hover styling obscures the menu item.

![image](https://user-images.githubusercontent.com/287050/162019928-d5ec85ce-6702-461e-a820-98fb60ce0ba7.png)

2022-04-06 16:14 UTC, benarmston commented on landing-page/types/headnode/layouts/navbar.html.erb
> +                          href="<%= prefix_url("/apps") %>/apps"
We don't need both `/apps` here.

2022-04-06 16:14 UTC, benarmston commented on landing-page/types/headnode/layouts/sidebar.html.erb
> +          <% title = "<span class=\"title\">#{app[:short_title] || app[:title]}></span>" %>
There's an extra `>` on this line (or somewhere).

![image](https://user-images.githubusercontent.com/287050/162019142-2e21b462-a9cf-414f-9f2c-eeb91f1b5aec.png)

2022-04-06 17:08 UTC, VoxSecundus commented
@benarmston As a suggestion to fix both the menu going off screen and the issue regarding menu alignment in `flight-webapp-components`, do you take any issue with having the menu be anchored to the bottom right of the menu instead of the bottom left?

2022-04-06 17:24 UTC, benarmston commented
> @benarmston As a suggestion to fix both the menu going off screen and the issue regarding menu alignment in `flight-webapp-components`, do you take any issue with having the menu be anchored to the bottom right of the menu instead of the bottom left?

Not immediately.  Give it a go and I'll see what it looks like.

2022-04-11 14:28 UTC, benarmston commented
I've pushed some changes making minor adjustments to the split toggle arrow padding.  Other than that this is looking good.  Ready to merge when the web app components work is.

2022-04-11 17:49 UTC, benarmston requested changes
After following through the flight direct branding dropdown item colour issues, I have some more comments on this PR.  These comments go hand-in-hand with those I've added to https://github.com/openflighthpc/flight-webapp-components/pull/7.

2022-04-11 17:49 UTC, benarmston commented on landing-page/types/alces-branding/content/styles/branding.css
>  }
I think we need a corresponding rule for `.navbar .dropdown-item` to set the colour to white.  That should fix the webapp issue dropdown item colour issue.

2022-04-11 17:49 UTC, benarmston commented on landing-page/types/alces-branding/content/styles/branding.css
>  }
The second of these rules applies the hover styling to the account menu.  Can you remove the `.navbar .dropdown-item:hover span` rule and make the `.navbar a.nav.dropdown-item:hover` rule also match the dropdown's in the new dropdown menu.

Perhaps make the selector more generic or perhaps add a second specific selector to the rule.

2022-04-11 17:49 UTC, benarmston commented on landing-page/types/alces-branding/content/styles/branding.css
> +}
I think the default padding-{left,right} of 24px is probably better.  Can you remove this please?

2022-04-11 17:49 UTC, benarmston commented on landing-page/types/headnode/layouts/navbar.html.erb
> +                                  class="dropdown-item nav-link nav-menu-button"
Can you remove the `nav-link` and `nav-menu-button` classes.  The bootstrap documentation doesn't add `nav-link` to its nav dropdown items (https://getbootstrap.com/docs/4.6/components/navs/#pills-with-dropdowns).  I don't think we need to either.

2022-04-11 17:50 UTC, benarmston commented
@VoxSecundus please be aware I added some commits to this PR when I thought it was good.  Please don't lose them.

2022-04-14 11:42 UTC, merged