Allow config packs to be display on the landing page
openflighthpc/flight-landing-page pull request #8
Opened 2021-05-27 13:54 UTC by WilliamMcCumstie

These config packs are based on the web applications but are for a slightly different purpose. `config-packs` have a list of links (`downloads`) instead of a web-application page.

The `config-packs` store there metadata file within: `/content/config-packs/<pack-name>.md`. The `pack-name` is assumed to be unique and nicely formattable into a URL.

The metadata file syntax is:

```
---
title: Demo config pack
short_title: Config pack
subtitle: Access the demo config pack
downloads:
  - <filename>
  - [<humanized-name>, <filename>]
---
Lorem ipsum dolor sit amet, consectetur adipiscing elit. ...
```

The landing page is not responsible for hosting the config files themselves. This is to allow the configs to be updated without the landing page being recompiled. Instead they rely on an external service (`nginx`) to serve content on its behalf.

By convention, the files need to be hosted at:
`/downloads/config-packs/<pack-name>/<filename>`

2021-06-02 14:29 UTC, benarmston commented
This is looking pretty good @WilliamMcCumstie.

I've had a play with my admin/ops hat on and I think that there are some improvements that we can make to the UI and to the UX in creating config packs.  Once you've made those changes I'll have another look with my dev hat on.

* The `a` tags in the downloads list group should be wrapped in a `span`.
  The `class` set on `a` should be moved the `span`.  This keeps the standard
  link styling.
  ```html
  <div class="list-group">
    <span class="list-group-item list-group-item-action">
      <a ...>...</a>
    </span>
  </div>
  ```

* The link should open in a new tab.  This can be done with
  ```html
  <a target="_blank" rel="noopener">...</a>
  ```

* I like the option to use a human readable file name.  The syntax doesn't
  seem quite right though.  The following would be clearer and allow for
  future expansion.
  ```yaml
  downloads:
    - file_name: xampl.tar.gz
      display_name: Tarball
  ```

* Following on from above, downloads should support an optional icon.
  Something like:
  ```yaml
  downloads:
    - file_name: xampl.tar.gz
      display_name: Tarball
      fa_icon: file-archive-o
  ```
  which should result in HTML like this:
  ```html
  <div class="list-group">
      <span class="list-group-item list-group-item-action">
          <i class="fa fa-file-o mr-1"></i>
          <a href="/downloads/config-packs/vpn/README.md">README.md</a>
      </span>
      <span class="list-group-item list-group-item-action">
          <i class="fa fa-file-archive-o mr-1"></i>
          <a href="/downloads/config-packs/vpn/vpn.tar.gz">vpn.tar.gz</a>
      </span>          
  </div>
  ```

* The directory for the config pack downloads should be created when the RPM
  is installed.  It took me too many attempt to get the downloads in the
  correct location.

* We should ship with a disabled example config pack.  Something like
  ```
  ---
  disabled: true
  title: An example config pack
  short_title: Example
  subtitle: An example config pack
  downloads:
    - README.md
    - [Tarball, example.tar.gz]
  ---
  This is an example config pack that you can copy and modify to create your own.
  
  The files listed above need to be stored in
  `/opt/flight/usr/share/www/downloads/config-packs/<PACK NAME>/`.  In this case
  that will be
  `/opt/flight/usr/share/www/downloads/config-packs/example/README.md` and
  `/opt/flight/usr/share/www/downloads/config-packs/example/example.tar.gz.md`.
  ```

* The above implies the ability to disable a config pack.

* The icons don't seem quite right.  Let's remove them.

* We need more vertical space between the end of the web app section and the
  "Config packs" header.


---

The look I'm aiming for is the one on the right rather than the one of the left.

![image](https://user-images.githubusercontent.com/287050/120498355-11ccd480-c3b7-11eb-921f-4a0550511bef.png)

2021-06-07 18:22 UTC, benarmston requested changes
Having an example config shipped and enabled has made reviewing this much easier.  Thanks.

It's looking much better than it was before.  However, the layout doesn't look quite right with multiple packs:

![image](https://user-images.githubusercontent.com/287050/121069151-11707700-c7c5-11eb-8ef0-b0618a206e08.png)

Something like this would be better:

![image](https://user-images.githubusercontent.com/287050/121069412-5a283000-c7c5-11eb-9cec-41c87cbe1517.png)

I got that with the following CSS changes:

```diff
--- default/content/styles/app.scss     2021-06-04 16:07:29.000000000 +0000
+++ overridden/content/styles/app.scss  2021-06-07 18:19:30.942296665 +0000
@@ -11,12 +11,20 @@
   grid-gap: .5rem;
 }
 
-.app-card-deck .app-card {
+.config-pack-card-deck {
+  display: grid;
+  grid-template-columns: repeat(auto-fit, minmax(400px, max-content));
+  grid-gap: .5rem;
+}
+
+.app-card-deck .app-card,
+.config-pack-card-deck .config-pack-card {
   margin: 0;
   min-height: 250px;
 }
 
-.app-card .card-body p:last-child {
+.app-card .card-body p:last-child,
+.config-pack-card .card-body p:last-child {
     margin-bottom: 0;
 }
```

Could you make that changes to `default/content/styles/app.scss` along with the other requests.

2021-06-08 14:25 UTC, WilliamMcCumstie commented on landing-page/types/headnode/content/config-packs/example.md.disabled
> +disabled: false # The .disabled file extension takes precedence
bb4d5ffaf1245bdccb162620f8ff68e97147f5d5

2021-06-08 14:25 UTC, WilliamMcCumstie commented on landing-page/types/headnode/content/config-packs.html.erb
> +    Your environment has the following tool packs installed and ready for use.
bb4d5ffaf1245bdccb162620f8ff68e97147f5d5

2021-06-08 15:28 UTC, WilliamMcCumstie commented
Rebased on master

2021-06-10 16:28 UTC, benarmston commented
I've added a few commits which do the following:

* Switch the various classes to data attributes.
* Use different text for disabled web suite links and disabled config pack links.
* Various copy changes.

This LGTM.

2021-06-10 16:29 UTC, merged